name: build and push development
#on: [push] # When pushing to any branch then run this action
on:
  push:
    branches: 
         #- development
          - staging
         #- production
jobs:
  dev-build-push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    environment: demo-workflow
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./backend/Dockerfile
        push: true
        #saat ini hanya untuk testing saja, dijadikan multiple tag.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:development,${{ secrets.DOCKERHUB_USERNAME }}/backend:staging, ${{ secrets.DOCKERHUB_USERNAME }}/backend:production
    
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./frontend/Dockerfile
        push: true
        #saat ini hanya untuk testing saja, dijadikan multiple tag.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:development, ${{ secrets.DOCKERHUB_USERNAME }}/frontend:staging, ${{ secrets.DOCKERHUB_USERNAME }}/frontend:production